name: Sync and Modify IP Lists

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 01:00 UTC 自动运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Clone MetaCubeX/meta-rules-dat (meta branch)
        run: git clone --branch meta https://github.com/MetaCubeX/meta-rules-dat.git --depth=1

      - name: Clone 666OS/YYDS (main branch)
        run: git clone --branch main https://github.com/666OS/YYDS.git yyds-repo --depth=1

      - name: Create ActionRules directory
        run: mkdir -p ActionRules

      - name: Process IP lists (add ,no-resolve)
        run: |
          for f in private google netflix telegram twitter; do
            awk '{ if ($0 ~ /^#/) print $0; else print $0",no-resolve" }' \
              meta-rules-dat/geo/geoip/classical/$f.list > ActionRules/$f.list
          done

      - name: Convert YAML files from 666OS/YYDS to list format with correct comment alignment
        run: |
          for f in XPTV download fix-direct; do
            src="yyds-repo/mihomo/rules/$f.yaml"
            dst="ActionRules/$f.list"
            # 处理 YAML 文件并去除不需要的行，确保注释行格式正确
            grep -vE '^(payload:|[[:space:]]*# PROCESS-NAME|[[:space:]]*- PROCESS-NAME|^$)' "$src" \
              | sed -E 's/^[[:space:]]*-[[:space:]]*//' \
              | sed 's/^[[:space:]]*#/#/' > "$dst"
          done

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git add ActionRules/*.list
          git commit -m "Auto update IP and rule lists with proper comment formatting" || echo "No changes"

          git remote remove origin
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}
