name: Sync and Modify IP Lists

on:
  schedule:
    - cron: "30 22 * * *" # 6:30 AM UTC+8
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Clone MetaCubeX/meta-rules-dat (meta branch)
        run: git clone --branch meta https://github.com/MetaCubeX/meta-rules-dat.git --depth=1

      - name: Clone blackmatrix7/ios_rule_script (master branch)
        run: git clone --branch master https://github.com/blackmatrix7/ios_rule_script.git --depth=1

      - name: Clone 666OS/YYDS (main branch)
        run: git clone --branch main https://github.com/666OS/YYDS.git yyds-repo --depth=1

      - name: Create ActionRules directories
        run: mkdir -p ActionRules ActionRules/copy

      - name: Process classical geoip IP files (add ,no-resolve)
        run: |
          for f in private google netflix telegram twitter; do
            awk '{ if ($0 ~ /^#/) print $0; else print $0",no-resolve" }' \
              meta-rules-dat/geo/geoip/classical/$f.list > ActionRules/${f}_ip.list
          done

      - name: Convert YAML rules from 666OS/YYDS to list format
        run: |
          for f in XPTV download fix-direct; do
            src="yyds-repo/mihomo/rules/$f.yaml"
            dst="ActionRules/$f.list"
            grep -vE '^(payload:|[[:space:]]*# PROCESS-NAME|[[:space:]]*- PROCESS-NAME|^$)' "$src" \
              | sed -E 's/^[[:space:]]*-[[:space:]]*//' \
              | sed 's/^[[:space:]]*#/#/' > "$dst"
          done

      - name: Copy geosite list files from MetaCubeX (case-insensitive)
        run: |
          shopt -s nocasematch
          cd meta-rules-dat/geo/geosite/classical
          for f in category-public-tracker private connectivity-check cn openai category-ai-!cn github twitter youtube apple-cn apple cloudflare-cn google onedrive microsoft category-games telegram netflix bilibili bahamut spotify pixiv gfw geolocation-!cn; do
            for file in *; do
              if [[ "${file,,}" == "$f.list" ]]; then
                cp "$file" ../../../../ActionRules/copy/
              fi
            done
          done

      - name: Copy geoip cn.list as cn_ip.list (case-insensitive)
        run: |
          shopt -s nocasematch
          for file in meta-rules-dat/geo/geoip/classical/*; do
            filename=$(basename "$file")
            if [[ "${filename,,}" == "cn.list" ]]; then
              cp "$file" ActionRules/copy/cn_ip.list
            fi
          done

      - name: Copy game.list from blackmatrix7 (case-insensitive)
        run: |
          shopt -s nocasematch
          for file in ios_rule_script/rule/Loon/Game/*; do
            filename=$(basename "$file")
            if [[ "${filename,,}" == "game.list" ]]; then
              cp "$file" ActionRules/copy/game.list
            fi
          done

      - name: Copy emby.list from YYDS (case-insensitive)
        run: |
          shopt -s nocasematch
          for file in yyds-repo/mihomo/rules/*; do
            filename=$(basename "$file")
            if [[ "${filename,,}" == "emby.list" ]]; then
              cp "$file" ActionRules/copy/emby.list
            fi
          done

      - name: Copy mrs files from MetaCubeX geoip and geosite (case-insensitive)
        run: |
          shopt -s nocasematch
          cd meta-rules-dat/geo/geoip/classical
          for f in private cn google netflix twitter telegram; do
            for file in *; do
              if [[ "${file,,}" == "$f.mrs" ]]; then
                cp "$file" ../../../../meta/MetaCubeX/geoip/
              fi
            done
          done
          cd ../geosite
          for f in category-public-tracker private connectivity-check cn openai category-ai-!cn github twitter youtube apple-cn apple cloudflare-cn google onedrive microsoft category-games telegram netflix bilibili bahamut spotify pixiv gfw geolocation-!cn; do
            for file in *; do
              if [[ "${file,,}" == "$f.mrs" ]]; then
                cp "$file" ../../../../meta/MetaCubeX/geosite/
              fi
            done
          done

      - name: Copy game yaml from blackmatrix7 (case-insensitive)
        run: |
          shopt -s nocasematch
          for file in ios_rule_script/rule/Clash/Game/*; do
            filename=$(basename "$file")
            if [[ "${filename,,}" == "game_no_resolve.yaml" ]]; then
              cp "$file" meta/blackmatrix7/
            fi
          done

      - name: Copy emby list from 666OS/YYDS (case-insensitive)
        run: |
          shopt -s nocasematch
          for file in yyds-repo/mihomo/rules/*; do
            filename=$(basename "$file")
            if [[ "${filename,,}" == "emby.list" ]]; then
              cp "$file" meta/666OS/
            fi
          done

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ActionRules meta
          git commit -m "Auto sync and rename IP/rule lists" || echo "No changes"
          git remote remove origin
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}

      - name: Record errors and send Telegram notification
        run: |
          if [ -f warning.md ]; then
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
            message=$(cat warning.md)
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d text="$message"
          fi
