name: Auto Update IP Lists

on:
  push:
    branches:
      - main  # 可以根据需要更改为你的默认分支
  schedule:
    - cron: '0 0 * * *'  # 每天自动运行一次（根据需要调整）

jobs:
  update-ip-lists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MetaCubeX/meta-rules-dat repo
      uses: actions/checkout@v3
      with:
        repository: MetaCubeX/meta-rules-dat
        ref: meta  # 使用指定的分支

    - name: List files in classical directory
      run: ls -l meta/geo/geoip/classical

    - name: Copy specific files from classical directory and list copied files
      run: |
        # 只复制需要的文件
        cp meta/geo/geoip/classical/{private.list,google.list,netflix.list,telegram.list,twitter.list} ./
        ls -l ./  # 列出复制到当前目录的文件

    - name: Commit and push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add *.list
        git commit -m "Auto update specific IP lists with ,no-resolve" || echo "No changes"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.ref_name }}
