name: Sync and Modify IP Lists

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 01:00 UTC 自动运行
  workflow_dispatch:     # 允许手动触发

# 解决方案
permissions:
  contents: write

jobs:
  update-lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Clone source repo
        run: git clone https://github.com/MetaCubeX/meta-rules-dat.git --depth=1

      - name: Process files
        run: |
          mkdir -p ip-lists
          for f in private google netflix telegram twitter; do
            cat meta-rules-dat/geo/geoip/classical/$f.list | sed 's/$/,no-resolve/' > ip-lists/$f.list
          done

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          cp -r ip-lists/* ./
          git add *.list
          git commit -m "Auto update IP lists with ,no-resolve" || echo "No changes"
          
          # 移除当前 origin 配置
          git remote remove origin
          
          # 添加带有 GH_TOKEN 的新 origin 地址
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          
          # 查看更新后的 remote 配置
          git remote -v
          
          # 推送到指定分支
          git push origin HEAD:${{ github.ref_name }}
